name = "betaplek"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "betaplek-db"
database_id = "your-database-id-here"

# Environment variables
[vars]
PAYLOAD_SECRET = "your-payload-secret-here"
NEXT_PUBLIC_SERVER_URL = "https://your-domain.com"

# R2 Storage bindings (if using R2 for media)
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "your-r2-bucket-name"

# Email configuration (if using Resend or similar)
# Note: These should be set as secrets in Cloudflare dashboard
# [secrets]
# SMTP_HOST = "smtp.resend.com"
# SMTP_USER = "your-smtp-user"
# SMTP_PASS = "your-smtp-password"
# EMAIL_FROM_ADDRESS = "noreply@yourdomain.com"
# EMAIL_FROM_NAME = "Betaplek"

# Build configuration for Next.js
[build]
command = "npm run build"
cwd = "."

# Pages configuration
pages_build_output_dir = ".next"
